export const CATEGORIES = [
   { id: 'thoisu', name: 'Thời Sự', slug: 'thoisu', color: '#E53E3E' },
   { id: 'thegioi', name: 'Thế Giới', slug: 'thegioi', color: '#3182CE' },
   { id: 'business', name: 'Kinh Doanh', slug: 'business', color: '#D4AF37' },
   { id: 'technology', name: 'Công Nghệ', slug: 'technology', color: '#4299E1' },
   { id: 'sports', name: 'Thể Thao', slug: 'sports', color: '#38A169' },
   { id: 'entertainment', name: 'Giải Trí', slug: 'entertainment', color: '#805AD5' },
   { id: 'health', name: 'Sức Khỏe', slug: 'health', color: '#DD6B20' },
   { id: 'education', name: 'Giáo Dục', slug: 'education', color: '#B7791F' },
   { id: 'travel', name: 'Du Lịch', slug: 'travel', color: '#2C7A7B' },
   { id: 'khoahoc', name: 'Khoa Học', slug: 'khoahoc', color: '#00B5D8' },
   { id: 'phapluat', name: 'Pháp Luật', slug: 'phapluat', color: '#4A5568' },
   { id: 'xe', name: 'Xe', slug: 'xe', color: '#718096' },
   { id: 'doisong', name: 'Đời Sống', slug: 'doisong', color: '#F6AD55' },
   { id: 'tamsu', name: 'Tâm Sự', slug: 'tamsu', color: '#ED64A6' },
   { id: 'ykien', name: 'Ý Kiến', slug: 'ykien', color: '#6B46C1' },
];

export const CATEGORY_MAP = {
   thoisu: { name: 'Thời Sự', color: '#E53E3E' },
   thegioi: { name: 'Thế Giới', color: '#3182CE' },
   business: { name: 'Kinh Doanh', color: '#D4AF37' },
   technology: { name: 'Công Nghệ', color: '#4299E1' },
   sports: { name: 'Thể Thao', color: '#38A169' },
   entertainment: { name: 'Giải Trí', color: '#805AD5' },
   health: { name: 'Sức Khỏe', color: '#DD6B20' },
   education: { name: 'Giáo Dục', color: '#B7791F' },
   travel: { name: 'Du Lịch', color: '#2C7A7B' },
   khoahoc: { name: 'Khoa Học', color: '#00B5D8' },
   phapluat: { name: 'Pháp Luật', color: '#4A5568' },
   xe: { name: 'Xe', color: '#718096' },
   doisong: { name: 'Đời Sống', color: '#F6AD55' },
   tamsu: { name: 'Tâm Sự', color: '#ED64A6' },
   ykien: { name: 'Ý Kiến', color: '#6B46C1' },
};
